// start-tor.cs - builds to start-tor.exe (compile with build-start-tor.ps1)
// Portable Tor launcher for Iran. Expected layout next to this exe:
//   start-tor.exe
//   data\
//     tor.exe  torrc.template  geoip  geoip6  transports
//     torrc          <- generated by this program from torrc.template + bridges
//     bridges\       <- obfs4_tested.txt, webtunnel_tested.txt, vanilla_tested.txt
//     data\          <- runtime state (tor.log, cached-*, keys)
// The user picks a connection mode (direct / webtunnel / obfs4 / vanilla); the
// program writes data\torrc and starts tor, then enables the Windows system
// proxy (HTTP 127.0.0.1:8118). Press Enter to stop and restore the proxy.
// Subcommands: --newcircuit, --stop, --bootstrap-only [mode].
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Net.Sockets;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using Microsoft.Win32;

namespace StartTor
{
    internal static class Program
    {
        private static readonly string AppDir =
            Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
        private static readonly string DataDir = Path.Combine(AppDir, "data");
        private static readonly string TorExe = Path.Combine(DataDir, "tor.exe");
        private static readonly string TorrcTemplate = Path.Combine(DataDir, "torrc.template");
        private static readonly string Torrc = Path.Combine(DataDir, "torrc");
        private static readonly string BridgesDir = Path.Combine(DataDir, "bridges");
        private static readonly string ModeFile = Path.Combine(DataDir, "mode.txt");
        private static readonly string TorLog = Path.Combine(DataDir, "data", "tor.log");
        private static readonly string ControlPassword = "newway-j7DJPvxLaS1H";
        private static readonly string ProxyKey =
            @"Software\Microsoft\Windows\CurrentVersion\Internet Settings";

        private const int InternetOptionSettingsChanged = 39;
        private const int InternetOptionRefresh = 37;

        private static readonly string[] ModeNames = { "direct", "webtunnel", "obfs4", "vanilla" };
        private static readonly string[] BridgeFiles = { "", "webtunnel_tested.txt", "obfs4_tested.txt", "vanilla_tested.txt" };

        private static Process torProc;
        private static bool cleaned;

        [DllImport("wininet.dll", SetLastError = true)]
        private static extern bool InternetSetOption(IntPtr h, int option, IntPtr buffer, int length);

        private static void SetSystemProxy(bool on)
        {
            try
            {
                using (RegistryKey k = Registry.CurrentUser.CreateSubKey(ProxyKey))
                {
                    k.SetValue("ProxyEnable", on ? 1 : 0, RegistryValueKind.DWord);
                    if (on)
                    {
                        k.SetValue("ProxyServer", "127.0.0.1:8118", RegistryValueKind.String);
                        k.SetValue("ProxyOverride", "<local>", RegistryValueKind.String);
                    }
                }
            }
            catch { }
            InternetSetOption(IntPtr.Zero, InternetOptionSettingsChanged, IntPtr.Zero, 0);
            InternetSetOption(IntPtr.Zero, InternetOptionRefresh, IntPtr.Zero, 0);
        }

        private static void Cleanup()
        {
            if (cleaned) return;
            cleaned = true;
            if (torProc != null)
            {
                try { if (!torProc.HasExited) { torProc.Kill(); torProc.WaitForExit(5000); } }
                catch { }
            }
            SetSystemProxy(false);
        }

        private static void WaitForKey()
        {
            try { Console.WriteLine("Press any key to exit..."); Console.ReadKey(true); }
            catch { }
        }

        private static string ReadLogTail(int bytes)
        {
            try
            {
                using (FileStream fs = new FileStream(TorLog, FileMode.Open,
                                                      FileAccess.Read, FileShare.ReadWrite))
                {
                    long start = Math.Max(0, fs.Length - bytes);
                    fs.Seek(start, SeekOrigin.Begin);
                    using (StreamReader sr = new StreamReader(fs, Encoding.UTF8, true))
                        return sr.ReadToEnd();
                }
            }
            catch { return ""; }
        }

        private static Process FindTor()
        {
            foreach (Process p in Process.GetProcessesByName("tor"))
            {
                try
                {
                    if (p.MainModule.FileName.Equals(TorExe, StringComparison.OrdinalIgnoreCase))
                        return p;
                }
                catch { }
            }
            return null;
        }

        private static bool ControlSend(string cmd)
        {
            try
            {
                using (TcpClient c = new TcpClient("127.0.0.1", 9051))
                {
                    NetworkStream s = c.GetStream();
                    StreamWriter w = new StreamWriter(s) { NewLine = "\r\n", AutoFlush = true };
                    StreamReader r = new StreamReader(s);
                    w.WriteLine("AUTHENTICATE \"" + ControlPassword + "\"");
                    if (!r.ReadLine().StartsWith("250")) return false;
                    w.WriteLine(cmd);
                    if (!r.ReadLine().StartsWith("250")) return false;
                    w.WriteLine("QUIT");
                    return true;
                }
            }
            catch { return false; }
        }

        private static int ParseMode(string s)
        {
            for (int i = 0; i < ModeNames.Length; i++)
                if (s.Equals(ModeNames[i], StringComparison.OrdinalIgnoreCase)) return i;
            return -1;
        }

        private static int ReadLastMode()
        {
            try { if (File.Exists(ModeFile)) return ParseMode(File.ReadAllText(ModeFile).Trim()); }
            catch { }
            return -1;
        }

        private static int ShowMenu()
        {
            int last = ReadLastMode();
            while (true)
            {
                Console.WriteLine();
                Console.WriteLine("  Connection mode:");
                Console.WriteLine("    1) Direct Tor");
                Console.WriteLine("    2) WebTunnel");
                Console.WriteLine("    3) Obfs4");
                Console.WriteLine("    4) Vanilla");
                Console.Write("  Choose 1-4 (Enter = " + (last >= 0 ? ModeNames[last] : "direct") + "): ");
                string input;
                try { input = Console.ReadLine(); }
                catch { return -1; }
                if (string.IsNullOrWhiteSpace(input)) return last >= 0 ? last : 0;
                int n;
                if (int.TryParse(input.Trim(), out n) && n >= 1 && n <= 4) return n - 1;
                int m = ParseMode(input.Trim());
                if (m >= 0) return m;
                Console.WriteLine("    Invalid choice, try again.");
            }
        }

        private static bool WriteTorrc(int mode)
        {
            if (!File.Exists(TorrcTemplate))
            {
                Console.WriteLine("[x] torrc.template not found in " + DataDir);
                return false;
            }
            string tmpl = File.ReadAllText(TorrcTemplate);
            int bridgeCount = 0;
            StringBuilder sb = new StringBuilder(tmpl.TrimEnd());
            if (mode > 0)
            {
                string bf = Path.Combine(BridgesDir, BridgeFiles[mode]);
                if (!File.Exists(bf))
                {
                    Console.WriteLine("[x] bridge file not found: " + bf);
                    return false;
                }
                var bridges = new List<string>();
                foreach (string line in File.ReadAllLines(bf))
                {
                    string t = line.Trim();
                    if (t.Length == 0 || t.StartsWith("#")) continue;
                    bridges.Add("Bridge " + t);
                }
                if (bridges.Count == 0)
                {
                    Console.WriteLine("[!] no usable bridge lines in " + bf);
                    return false;
                }
                sb.AppendLine();
                sb.AppendLine();
                sb.AppendLine("# --- bridges: " + ModeNames[mode] + " ---");
                sb.AppendLine("UseBridges 1");
                foreach (string b in bridges) sb.AppendLine(b);
                bridgeCount = bridges.Count;
            }
            File.WriteAllText(Torrc, sb.ToString(), new UTF8Encoding(false));
            try { File.WriteAllText(ModeFile, ModeNames[mode], new UTF8Encoding(false)); }
            catch { }
            Console.WriteLine("[i] torrc written (" + ModeNames[mode] +
                              (mode > 0 ? ", " + bridgeCount + " bridges" : "") + ")");
            return true;
        }

        private static int StopTor()
        {
            Process p = FindTor();
            if (p != null)
            {
                try { p.Kill(); p.WaitForExit(5000); } catch { }
                SetSystemProxy(false);
                Console.WriteLine("Tor stopped; system proxy restored.");
            }
            else
            {
                Console.WriteLine("No tor from this folder is running.");
            }
            return 0;
        }

        private static int Main(string[] args)
        {
            Console.Title = "Tor Iran Portable";

            if (args.Length > 0 && args[0] == "--newcircuit")
            {
                Console.WriteLine(ControlSend("SIGNAL NEWNYM")
                    ? "New identity requested (NEWNYM)."
                    : "No tor control port on 127.0.0.1:9051. Is tor running?");
                return 0;
            }
            if (args.Length > 0 && args[0] == "--stop")
            {
                return StopTor();
            }

            int mode = -1;
            bool bootstrapOnly = false;
            bool genOnly = false;
            foreach (string a in args)
            {
                if (a == "--bootstrap-only" || a == "-t") bootstrapOnly = true;
                else if (a == "--gen-torrc-only") genOnly = true;
                else { int m = ParseMode(a); if (m >= 0) mode = m; }
            }
            if (mode < 0) mode = ShowMenu();
            if (mode < 0) { Console.WriteLine("[x] no mode selected."); return 1; }

            Console.WriteLine();
            Console.WriteLine("Tor Portable for Iran (official tor 0.4.9.11)");
            Console.WriteLine("  mode    : " + ModeNames[mode]);
            Console.WriteLine("  data dir: " + DataDir);
            Console.WriteLine();

            if (!File.Exists(TorExe))
            {
                Console.WriteLine("[x] tor.exe not found in " + DataDir);
                WaitForKey();
                return 1;
            }
            if (!WriteTorrc(mode)) { WaitForKey(); return 1; }
            if (genOnly)
            {
                Console.WriteLine("[i] torrc written only (test mode, tor not started): " + Torrc);
                return 0;
            }

            if (FindTor() != null)
            {
                Console.WriteLine("[x] tor is already running from this folder.");
                Console.WriteLine("    Use:  start-tor.exe --stop  or  start-tor.exe --newcircuit");
                return 1;
            }

            Console.CancelKeyPress += delegate(object sender, ConsoleCancelEventArgs e)
            {
                e.Cancel = true;
                Cleanup();
                Environment.Exit(0);
            };

            Directory.CreateDirectory(Path.Combine(DataDir, "data"));
            try { if (File.Exists(TorLog)) File.Delete(TorLog); } catch { }

            ProcessStartInfo psi = new ProcessStartInfo
            {
                FileName = TorExe,
                Arguments = "-f \"torrc\"",
                WorkingDirectory = DataDir,
                UseShellExecute = false,
                CreateNoWindow = true
            };

            try { torProc = Process.Start(psi); }
            catch (Exception ex)
            {
                Console.WriteLine("[x] failed to start tor: " + ex.Message);
                WaitForKey();
                return 1;
            }

            Console.WriteLine("[i] tor started (PID " + torProc.Id + "), bootstrapping...");

            DateTime deadline = DateTime.UtcNow.AddMinutes(10);
            int lastPct = -1;
            bool done = false;
            bool exited = false;

            while (!done && !exited && DateTime.UtcNow < deadline)
            {
                torProc.Refresh();
                if (torProc.HasExited) { exited = true; break; }

                MatchCollection ms = Regex.Matches(ReadLogTail(2000), "Bootstrapped (\\d+)%");
                if (ms.Count > 0)
                {
                    Match m = ms[ms.Count - 1];
                    int pct = int.Parse(m.Groups[1].Value);
                    if (pct >= 100) { done = true; break; }
                    if (pct != lastPct)
                    {
                        Console.WriteLine("    Bootstrapped " + pct + "% ...");
                        lastPct = pct;
                    }
                }
                Thread.Sleep(2000);
            }

            if (exited)
            {
                Console.WriteLine("[x] tor exited with code " + torProc.ExitCode + ".");
                Console.WriteLine("    Last log lines:");
                Console.WriteLine(ReadLogTail(1500));
                Cleanup();
                WaitForKey();
                return 1;
            }

            if (!done)
            {
                Console.WriteLine("[x] bootstrap did not reach 100% in 10 minutes.");
                Console.WriteLine("    Try a different mode (start-tor.exe webtunnel|obfs4|vanilla).");
                Console.WriteLine("    Last log lines:");
                Console.WriteLine(ReadLogTail(1500));
                Cleanup();
                WaitForKey();
                return 1;
            }

            Console.WriteLine();
            Console.WriteLine("Bootstrapped 100% - Tor is UP.");

            if (bootstrapOnly)
            {
                Console.WriteLine("Test mode: stopping tor (no proxy change).");
                Cleanup();
                return 0;
            }

            SetSystemProxy(true);
            Console.WriteLine("System proxy set to 127.0.0.1:8118");
            Console.WriteLine("  SOCKS5 127.0.0.1:9050");
            Console.WriteLine("  HTTP   127.0.0.1:8118");
            Console.WriteLine("  DNS    127.0.0.1:53530");
            Console.WriteLine();
            Console.WriteLine("Press Enter to stop Tor and restore the system proxy...");
            try { Console.ReadLine(); } catch { }

            Cleanup();
            Console.WriteLine("Tor stopped; system proxy restored.");
            WaitForKey();
            return 0;
        }
    }
}
