// start-tor.cs - builds to start-tor.exe (compile with build-start-tor.ps1)
// TorBoost launcher - portable Tor client tuned for speed. Expected layout:
//   start-tor.exe
//   data\
//     tor.exe  torrc.template  geoip  geoip6  transports
//     torrc          <- generated by this program from torrc.template + bridges
//     bridges\       <- obfs4_tested.txt, webtunnel_tested.txt, vanilla_tested.txt
//     data\          <- runtime state (tor.log, cached-*, keys)
// The user picks a connection mode (direct / webtunnel / obfs4 / vanilla); the
// program writes data\torrc and starts tor. Tor is NOT set as the system proxy
// automatically: press P to toggle the Windows system proxy
// (HTTP 127.0.0.1:8118) on/off. T toggles TUN mode (routes ALL system traffic
// through tor - needs Administrator, spawns the elevated tun-helper.exe).
// C stops tor (TUN + system proxy + core) and returns to the main menu.
// Subcommands: --newcircuit, --stop, --tun-off, --tun-status, --update-bridges,
// --bootstrap-only [mode].
// A trailing `proxy` or `tun` argument auto-enables the Windows system proxy or
// TUN mode right after bootstrap, e.g. `start-tor.exe obfs4 aggressive proxy`.
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using Microsoft.Win32;

namespace StartTor
{
    internal static class Program
    {
        private static readonly string AppDir =
            Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
        private static readonly string DataDir = Path.Combine(AppDir, "data");
        private static readonly string TorExe = Path.Combine(DataDir, "tor.exe");
        private static readonly string TorrcTemplate = Path.Combine(DataDir, "torrc.template");
        private static readonly string Torrc = Path.Combine(DataDir, "torrc");
        private static readonly string BridgesDir = Path.Combine(DataDir, "bridges");
        private static readonly string ModeFile = Path.Combine(DataDir, "mode.txt");
        private static readonly string StrategyFile = Path.Combine(DataDir, "strategy.txt");
        private static readonly string[] StrategyNames = { "standard", "balanced", "aggressive", "ultimate" };
        private static readonly string[] StrategyDesc =
        {
            "stock config, most compatible",
            "long-lived reused circuits",
            "many guards + fast scheduler",
            "max concurrency + per-stream circuits"
        };
        private static readonly string[][] StrategyTorrc =
        {
            /* standard */ new string[0],
            /* balanced */ new[]
            {
                "MaxCircuitDirtiness 86400",
                "CircuitsAvailableTimeout 1440",
                "CircuitStreamTimeout 30"
            },
            /* aggressive */ new[]
            {
                "MaxCircuitDirtiness 86400",
                "CircuitsAvailableTimeout 1440",
                "CircuitStreamTimeout 30",
                "NumEntryGuards 15",
                "NumPrimaryGuards 15",
                "Schedulers KISTLite,Vanilla",
                "KISTSchedRunInterval 5 msec"
            },
            /* ultimate */ new[]
            {
                "MaxCircuitDirtiness 86400",
                "CircuitsAvailableTimeout 1440",
                "CircuitStreamTimeout 30",
                "NumEntryGuards 15",
                "NumPrimaryGuards 15",
                "Schedulers KISTLite,Vanilla",
                "KISTSchedRunInterval 5 msec",
                "MaxClientCircuitsPending 128",
                "TokenBucketRefillInterval 1 msec",
                "CircuitPriorityHalflife 5",
                "SocksTimeout 120"
            }
        };
        private static readonly string TorLog = Path.Combine(DataDir, "data", "tor.log");
        private static readonly string ControlCookie = Path.Combine(DataDir, "data", "control_auth_cookie");
        private static readonly string ProxyKey =
            @"Software\Microsoft\Windows\CurrentVersion\Internet Settings";

        private const int InternetOptionSettingsChanged = 39;
        private const int InternetOptionRefresh = 37;

        private static readonly string[] ModeNames = { "obfs4", "webtunnel", "vanilla", "direct" };
        private static readonly string[] BridgeFiles = { "obfs4_tested.txt", "webtunnel_tested.txt", "vanilla_tested.txt", "" };
        private static readonly string[] AllBridgeFiles = { "obfs4_tested.txt", "webtunnel_tested.txt", "vanilla_tested.txt" };
        private const string BridgesBaseUrl =
            "https://raw.githubusercontent.com/Delta-Kronecker/Tor-Bridges-Collector/refs/heads/main/bridge";

        private static readonly string TunHelperExe = Path.Combine(DataDir, "tun-helper.exe");
        private static readonly string TunStateFile = Path.Combine(DataDir, "tun-state.txt");
        private static readonly string TunStopFile = Path.Combine(DataDir, "tun-stop.txt");
        private static readonly string TunResultFile = Path.Combine(DataDir, "tun-result.txt");

        // Ports used by this program's tor (torrc.template / torrc.boost).
        // Occupied ports at startup mean a previous tor instance is still alive.
        private static readonly int[] TcpPorts = { 9050, 9051, 8118 };
        private const int UdpDnsPort = 53530;

        private static Process torProc;
        private static bool cleaned;
        private static int progressLineLen;

        [DllImport("wininet.dll", SetLastError = true)]
        private static extern bool InternetSetOption(IntPtr h, int option, IntPtr buffer, int length);

        private static bool ProxyIsOurs()
        {
            try
            {
                using (RegistryKey k = Registry.CurrentUser.OpenSubKey(ProxyKey))
                {
                    if (k == null) return false;
                    object en = k.GetValue("ProxyEnable");
                    object ps = k.GetValue("ProxyServer");
                    return en is int && (int)en == 1 &&
                           ps is string &&
                           ((string)ps).IndexOf("127.0.0.1:8118",
                                                StringComparison.OrdinalIgnoreCase) >= 0;
                }
            }
            catch { return false; }
        }

        private static void SetSystemProxy(bool on)
        {
            if (!on && !ProxyIsOurs()) return;
            try
            {
                using (RegistryKey k = Registry.CurrentUser.CreateSubKey(ProxyKey))
                {
                    k.SetValue("ProxyEnable", on ? 1 : 0, RegistryValueKind.DWord);
                    if (on)
                    {
                        k.SetValue("ProxyServer", "127.0.0.1:8118", RegistryValueKind.String);
                        k.SetValue("ProxyOverride", "<local>", RegistryValueKind.String);
                    }
                }
            }
            catch { }
            InternetSetOption(IntPtr.Zero, InternetOptionSettingsChanged, IntPtr.Zero, 0);
            InternetSetOption(IntPtr.Zero, InternetOptionRefresh, IntPtr.Zero, 0);
        }

        private static bool IsAdmin()
        {
            try
            {
                using (var id = System.Security.Principal.WindowsIdentity.GetCurrent())
                {
                    var p = new System.Security.Principal.WindowsPrincipal(id);
                    return p.IsInRole(System.Security.Principal.WindowsBuiltInRole.Administrator);
                }
            }
            catch { return false; }
        }

        private static string ReadTunState()
        {
            try
            {
                if (File.Exists(TunStateFile))
                {
                    foreach (string line in File.ReadAllLines(TunStateFile))
                        if (line.TrimStart().StartsWith("status="))
                            return line.TrimStart().Substring(7).Trim();
                }
            }
            catch { }
            return "off";
        }

        // TUN counts as ON when the state file says so OR a tun-helper keeper is
        // actually running. The state file can be emptied/left stale by a failed
        // enable; only trusting it made "T" keep re-enabling instead of turning
        // the tunnel off.
        private static bool TunActive()
        {
            if (ReadTunState() == "on") return true;
            try
            {
                foreach (Process p in Process.GetProcessesByName("tun-helper"))
                    if (!p.HasExited &&
                        p.MainModule.FileName.Equals(TunHelperExe, StringComparison.OrdinalIgnoreCase))
                        return true;
            }
            catch { }
            return false;
        }

        private static string ReadTunResult()
        {
            try { if (File.Exists(TunResultFile)) return File.ReadAllText(TunResultFile).Trim(); }
            catch { }
            return "";
        }

        private static bool SpawnElevated(string args, bool wait)
        {
            try
            {
                // Tell the elevated helper where the data dir is. It used to sit
                // next to data\ and derive it from its own location; now it ships
                // inside data\, so this keeps state/result/stop files in sync.
                Environment.SetEnvironmentVariable("TUN_DATA_DIR", DataDir,
                                                   EnvironmentVariableTarget.Process);
                var psi = new ProcessStartInfo
                {
                    FileName = TunHelperExe,
                    Arguments = args,
                    UseShellExecute = true,
                    Verb = "runas",
                    WindowStyle = ProcessWindowStyle.Hidden
                };
                using (Process p = Process.Start(psi))
                {
                    if (wait) p.WaitForExit();
                }
                return true;
            }
            catch { return false; }
        }

        private static void ToggleTun()
        {
            if (TunActive())
            {
                TurnTunOff();
            }
            else
            {
                if (!IsAdmin()) Console.WriteLine("  [i] TUN mode needs Administrator - accept the UAC prompt.");
                Console.WriteLine("  [i] Turning TUN ON (all traffic via Tor)...");
                if (!SpawnElevated("on", false))
                {
                    Console.WriteLine("  [i] TUN enable cancelled.");
                    return;
                }
                string last = "";
                for (int i = 0; i < 20; i++)
                {
                    Thread.Sleep(1000);
                    last = ReadTunResult();
                    if (last.StartsWith("on:") || last.StartsWith("error:")) break;
                }
                Console.WriteLine("  [i] " + last);
            }
        }

        private static void TurnTunOff()
        {
            Console.WriteLine("  [i] Turning TUN OFF...");
            try { File.WriteAllText(TunStopFile, "stop", new UTF8Encoding(false)); } catch { }
            for (int i = 0; i < 40 && TunActive(); i++) Thread.Sleep(500);
            if (!TunActive()) { Console.WriteLine("  [i] TUN OFF"); return; }
            Console.WriteLine("  [i] keeper did not stop; forcing teardown (UAC)...");
            if (SpawnElevated("off", true))
                Console.WriteLine("  [i] " + (TunActive() ? "TUN still ON - check data\\tun-result.txt" : "TUN OFF"));
            else
                Console.WriteLine("  [i] teardown cancelled - TUN still ON");
        }

        private static void Cleanup()
        {
            if (cleaned) return;
            cleaned = true;
            if (TunActive())
            {
                try { File.WriteAllText(TunStopFile, "stop", new UTF8Encoding(false)); } catch { }
                for (int i = 0; i < 8; i++)
                {
                    Thread.Sleep(500);
                    if (!TunActive()) break;
                }
                if (TunActive())
                    try { SpawnElevated("off", true); } catch { }
            }
            if (torProc != null)
            {
                try { if (!torProc.HasExited) { torProc.Kill(); torProc.WaitForExit(5000); } }
                catch { }
            }
            SetSystemProxy(false);
        }

        private static void WaitForKey()
        {
            try { Console.WriteLine("Press any key to exit..."); Console.ReadKey(true); }
            catch { }
        }

        private static string ReadLogTail(int bytes)
        {
            try
            {
                using (FileStream fs = new FileStream(TorLog, FileMode.Open,
                                                      FileAccess.Read, FileShare.ReadWrite))
                {
                    long start = Math.Max(0, fs.Length - bytes);
                    fs.Seek(start, SeekOrigin.Begin);
                    using (StreamReader sr = new StreamReader(fs, Encoding.UTF8, true))
                        return sr.ReadToEnd();
                }
            }
            catch { return ""; }
        }

        private static Process FindTor()
        {
            foreach (Process p in Process.GetProcessesByName("tor"))
            {
                try
                {
                    if (p.MainModule.FileName.Equals(TorExe, StringComparison.OrdinalIgnoreCase))
                        return p;
                }
                catch { }
            }
            return null;
        }

        private static string CookieHex()
        {
            try
            {
                if (!File.Exists(ControlCookie)) return null;
                byte[] cookie = File.ReadAllBytes(ControlCookie);
                var sb = new StringBuilder(cookie.Length * 2);
                foreach (byte b in cookie) sb.Append(b.ToString("x2"));
                return sb.ToString();
            }
            catch { return null; }
        }

        private static bool ControlSend(string cmd)
        {
            try
            {
                string hex = CookieHex();
                if (hex == null) return false;
                using (TcpClient c = new TcpClient("127.0.0.1", 9051))
                {
                    NetworkStream s = c.GetStream();
                    StreamWriter w = new StreamWriter(s) { NewLine = "\r\n", AutoFlush = true };
                    StreamReader r = new StreamReader(s);
                    w.WriteLine("AUTHENTICATE " + hex);
                    if (!r.ReadLine().StartsWith("250")) return false;
                    w.WriteLine(cmd);
                    if (!r.ReadLine().StartsWith("250")) return false;
                    w.WriteLine("QUIT");
                    return true;
                }
            }
            catch { return false; }
        }

        private static int ParseMode(string s)
        {
            for (int i = 0; i < ModeNames.Length; i++)
                if (s.Equals(ModeNames[i], StringComparison.OrdinalIgnoreCase)) return i;
            return -1;
        }

        private static int ReadLastMode()
        {
            try { if (File.Exists(ModeFile)) return ParseMode(File.ReadAllText(ModeFile).Trim()); }
            catch { }
            return -1;
        }

        private static int ParseStrategy(string s)
        {
            for (int i = 0; i < StrategyNames.Length; i++)
                if (s.Equals(StrategyNames[i], StringComparison.OrdinalIgnoreCase)) return i;
            return -1;
        }

        private static int ReadLastStrategy()
        {
            try { if (File.Exists(StrategyFile)) return ParseStrategy(File.ReadAllText(StrategyFile).Trim()); }
            catch { }
            return -1;
        }

        private static void WriteStrategyFile(int strategy)
        {
            try { File.WriteAllText(StrategyFile, StrategyNames[strategy], new UTF8Encoding(false)); }
            catch { }
        }

        // Strategy for a run: env override (bench) > saved choice > standard.
        private static int ResolveStrategy()
        {
            string env = Environment.GetEnvironmentVariable("BENCH_STRATEGY");
            if (!string.IsNullOrEmpty(env))
            {
                int s = ParseStrategy(env);
                if (s >= 0) return s;
            }
            int last = ReadLastStrategy();
            return last >= 0 ? last : 0;
        }

        private static int ShowMenu()
        {
            int last = ReadLastMode();
            while (true)
            {
                Console.WriteLine();
                Console.WriteLine("  Connection mode:");
                Console.WriteLine("    1) Obfs4");
                Console.WriteLine("    2) WebTunnel");
                Console.WriteLine("    3) Vanilla");
                Console.WriteLine("    4) Direct Tor");
                Console.Write("  Choose 1-4 (Enter = " + ModeNames[last >= 0 ? last : 0] + "): ");
                string input;
                try { input = Console.ReadLine(); }
                catch { return -1; }
                if (string.IsNullOrWhiteSpace(input)) return last >= 0 ? last : 0;
                int n;
                if (int.TryParse(input.Trim(), out n) && n >= 1 && n <= 4) return n - 1;
                int m = ParseMode(input.Trim());
                if (m >= 0) return m;
                Console.WriteLine("    Invalid choice, try again.");
            }
        }

        private static int ShowStrategyMenu()
        {
            int last = ReadLastStrategy();
            while (true)
            {
                Console.WriteLine();
                Console.WriteLine("  Strategy level:");
                for (int i = 0; i < StrategyNames.Length; i++)
                {
                    string star = i == 0 ? "" : "  ";
                    Console.WriteLine("    " + (i + 1) + ") " + StrategyNames[i].PadRight(10) +
                                      " - " + StrategyDesc[i]);
                }
                Console.Write("  Choose 1-" + StrategyNames.Length +
                              " (Enter = " + StrategyNames[last >= 0 ? last : 0] + "): ");
                string input;
                try { input = Console.ReadLine(); }
                catch { return -1; }
                if (string.IsNullOrWhiteSpace(input)) return last >= 0 ? last : 0;
                int n;
                if (int.TryParse(input.Trim(), out n) && n >= 1 && n <= StrategyNames.Length) return n - 1;
                int s = ParseStrategy(input.Trim());
                if (s >= 0) return s;
                Console.WriteLine("    Invalid choice, try again.");
            }
        }

        private static void WriteModeFile(int mode)
        {
            try { File.WriteAllText(ModeFile, ModeNames[mode], new UTF8Encoding(false)); }
            catch { }
        }

        // Interactive startup: pick connection mode and strategy level, then start.
        private static void ShowMainMenu(out int mode, out int strategy)
        {
            mode = ReadLastMode();
            if (mode < 0) mode = 0;
            strategy = ReadLastStrategy();
            if (strategy < 0) strategy = 0;
            while (true)
            {
                Console.WriteLine();
                Console.WriteLine("  TorBoost");
                Console.WriteLine("  ================");
                Console.WriteLine("    1) Connection mode   : " + ModeNames[mode]);
                Console.WriteLine("    2) Strategy level    : " + StrategyNames[strategy] +
                                  "  - " + StrategyDesc[strategy]);
                Console.WriteLine("    3) Start Tor");
                Console.WriteLine("    4) Exit");
                Console.Write("  Choose 1-4 (Enter = 3): ");
                string input;
                try { input = Console.ReadLine(); }
                catch { mode = -1; return; }
                if (string.IsNullOrWhiteSpace(input)) return;
                int n;
                if (int.TryParse(input.Trim(), out n))
                {
                    if (n == 1)
                    {
                        int m = ShowMenu();
                        if (m >= 0) { mode = m; WriteModeFile(mode); }
                    }
                    else if (n == 2)
                    {
                        int s = ShowStrategyMenu();
                        if (s >= 0) { strategy = s; WriteStrategyFile(strategy); }
                    }
                    else if (n == 3) return;
                    else if (n == 4) { mode = -1; return; }
                    else Console.WriteLine("    Invalid choice, try again.");
                }
                else
                {
                    int m = ParseMode(input.Trim());
                    if (m >= 0) { mode = m; WriteModeFile(mode); }
                    else
                    {
                        int s = ParseStrategy(input.Trim());
                        if (s >= 0) { strategy = s; WriteStrategyFile(strategy); }
                        else Console.WriteLine("    Invalid choice, try again.");
                    }
                }
            }
        }

        private static bool WriteTorrc(int mode, int strategy)
        {
            if (!File.Exists(TorrcTemplate))
            {
                Console.WriteLine("[x] torrc.template not found in " + DataDir);
                return false;
            }
            string tmpl = File.ReadAllText(TorrcTemplate);
            int bridgeCount = 0;
            StringBuilder sb = new StringBuilder(tmpl.TrimEnd());
            if (BridgeFiles[mode].Length > 0)
            {
                string bf = Path.Combine(BridgesDir, BridgeFiles[mode]);
                if (!File.Exists(bf))
                {
                    Console.WriteLine("[x] bridge file not found: " + bf);
                    return false;
                }
                var bridges = new List<string>();
                foreach (string line in File.ReadAllLines(bf))
                {
                    string t = line.Trim();
                    if (t.Length == 0 || t.StartsWith("#")) continue;
                    bridges.Add("Bridge " + t);
                }
                if (bridges.Count == 0)
                {
                    Console.WriteLine("[!] no usable bridge lines in " + bf);
                    return false;
                }
                sb.AppendLine();
                sb.AppendLine();
                sb.AppendLine("# --- bridges: " + ModeNames[mode] + " ---");
                sb.AppendLine("UseBridges 1");
                foreach (string b in bridges) sb.AppendLine(b);
                bridgeCount = bridges.Count;
            }
            if (strategy >= 0 && strategy < StrategyNames.Length && StrategyTorrc[strategy].Length > 0)
            {
                sb.AppendLine();
                sb.AppendLine();
                sb.AppendLine("# --- strategy: " + StrategyNames[strategy] + " ---");
                foreach (string line in StrategyTorrc[strategy]) sb.AppendLine(line);
            }
            File.WriteAllText(Torrc, sb.ToString(), new UTF8Encoding(false));
            try { File.WriteAllText(ModeFile, ModeNames[mode], new UTF8Encoding(false)); }
            catch { }
            try { WriteStrategyFile(strategy); }
            catch { }
            Console.WriteLine("[i] torrc written (" + ModeNames[mode] +
                              ", strategy " + StrategyNames[strategy] +
                              (BridgeFiles[mode].Length > 0 ? ", " + bridgeCount + " bridges" : "") + ")");
            return true;
        }

        private static int CountBridgeLines(string path)
        {
            int n = 0;
            foreach (string line in File.ReadAllLines(path))
            {
                string t = line.Trim();
                if (t.Length == 0 || t.StartsWith("#")) continue;
                if (t.Contains("2001:db8")) continue;
                n++;
            }
            return n;
        }

        private static int UpdateBridges()
        {
            try
            {
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            }
            catch { }

            Directory.CreateDirectory(BridgesDir);
            Console.WriteLine("Updating bridge files from " + BridgesBaseUrl);
            Console.WriteLine("  -> " + BridgesDir);
            Console.WriteLine();

            int ok = 0;
            foreach (string f in AllBridgeFiles)
            {
                string dest = Path.Combine(BridgesDir, f);
                string tmp = dest + ".tmp";
                string url = BridgesBaseUrl + "/" + f;
                try
                {
                    using (WebClient wc = new WebClient())
                    {
                        wc.Headers[HttpRequestHeader.UserAgent] = "start-tor-updater/1.0";
                        wc.DownloadFile(url, tmp);
                    }
                    int n = CountBridgeLines(tmp);
                    if (n == 0)
                    {
                        Console.WriteLine("[!] " + f + ": downloaded file has no usable bridges - keeping old.");
                        try { File.Delete(tmp); } catch { }
                        continue;
                    }
                    File.Copy(tmp, dest, true);
                    try { File.Delete(tmp); } catch { }
                    Console.WriteLine("[i] " + f + ": " + n + " bridges - updated.");
                    ok++;
                }
                catch (Exception ex)
                {
                    Console.WriteLine("[x] " + f + ": " + ex.Message);
                }
            }

            Console.WriteLine();
            if (ok == AllBridgeFiles.Length)
            {
                Console.WriteLine("All bridge files are up to date.");
                return 0;
            }
            Console.WriteLine("Updated " + ok + " of " + AllBridgeFiles.Length +
                              " bridge files (restart tor to use the new bridges).");
            return ok > 0 ? 0 : 1;
        }

        private static string FormatSpeed(double bytesPerSec)
        {
            if (bytesPerSec >= 1024 * 1024)
                return (bytesPerSec / (1024 * 1024)).ToString("0.00") + " MB/s";
            if (bytesPerSec >= 1024)
                return (bytesPerSec / 1024).ToString("0.0") + " KB/s";
            return bytesPerSec.ToString("0") + " B/s";
        }

        private static void SpeedTest()
        {
            try { ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; }
            catch { }

            Console.WriteLine();
            Console.WriteLine("Speed test: downloading 10 MB through Tor (HTTP 127.0.0.1:8118)...");
            try
            {
                HttpWebRequest req = (HttpWebRequest)WebRequest.Create(
                    "https://speed.cloudflare.com/__down?bytes=10000000");
                req.Proxy = new WebProxy("127.0.0.1", 8118);
                req.Method = "GET";
                req.Timeout = 60000;
                req.ReadWriteTimeout = 60000;
                req.UserAgent = "start-tor-speedtest/1.0";

                using (WebResponse resp = req.GetResponse())
                using (Stream s = resp.GetResponseStream())
                {
                    byte[] buf = new byte[64 * 1024];
                    long total = 0;
                    Stopwatch sw = Stopwatch.StartNew();
                    long lastBytes = 0;
                    long lastTicks = sw.ElapsedTicks;
                    double inst = 0;
                    int n;
                    while ((n = s.Read(buf, 0, buf.Length)) > 0)
                    {
                        total += n;
                        long now = sw.ElapsedTicks;
                        if (now - lastTicks >= Stopwatch.Frequency)
                        {
                            inst = (total - lastBytes) /
                                   ((now - lastTicks) / (double)Stopwatch.Frequency);
                            lastBytes = total;
                            lastTicks = now;
                            Console.WriteLine("    " + total.ToString("#,0") + " bytes  (" + FormatSpeed(inst) + ")");
                        }
                    }
                    sw.Stop();

                    if (total > lastBytes)
                        inst = (total - lastBytes) /
                               ((sw.ElapsedTicks - lastTicks) / (double)Stopwatch.Frequency);
                    double avg = total / sw.Elapsed.TotalSeconds;

                    Console.WriteLine();
                    Console.WriteLine("Done: " + total.ToString("#,0") + " bytes in " +
                                      sw.Elapsed.TotalSeconds.ToString("0.0") + " s");
                    Console.WriteLine("  average speed    : " + FormatSpeed(avg));
                    Console.WriteLine("  instantaneous    : " + FormatSpeed(inst));
                    Console.WriteLine("  (avg MB/s = " + (avg / (1024 * 1024)).ToString("0.00") + ")");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("[x] speed test failed: " + ex.Message);
            }
        }

        // Opens a raw SOCKS5 (RFC 1928) connection through Tor's SOCKS port
        // (127.0.0.1:9050). A unique `username` per connection makes tor's
        // IsolateSOCKSAuth isolation give every stream its own circuit, which is
        // what turns N parallel downloads into N parallel Tor paths instead of
        // N streams sharing one circuit.
        private static NetworkStream Socks5Connect(string host, int port, string username)
        {
            TcpClient tc = new TcpClient();
            tc.Connect(IPAddress.Loopback, 9050);
            NetworkStream ns = tc.GetStream();
            // greeting: VER=5, NMETHODS=2, methods = no-auth(0), user/pass(2)
            byte[] g = { 5, 2, 0, 2 };
            ns.Write(g, 0, g.Length);
            byte[] gm = new byte[2];
            if (ns.Read(gm, 0, 2) != 2 || gm[0] != 5) { tc.Close(); return null; }
            if (gm[1] == 2)
            {
                byte[] u = Encoding.UTF8.GetBytes(username);
                byte[] p = Encoding.UTF8.GetBytes("torb");
                ns.WriteByte(1);
                ns.WriteByte((byte)u.Length);
                ns.Write(u, 0, u.Length);
                ns.WriteByte((byte)p.Length);
                ns.Write(p, 0, p.Length);
                byte[] au = new byte[2];
                if (ns.Read(au, 0, 2) != 2 || au[1] != 0) { tc.Close(); return null; }
            }
            else if (gm[1] != 0)
            {
                tc.Close();
                return null;
            }
            byte[] hb = Encoding.ASCII.GetBytes(host);
            List<byte> req = new List<byte>();
            req.Add(5); req.Add(1); req.Add(0); req.Add(3); req.Add((byte)hb.Length);
            req.AddRange(hb);
            req.Add((byte)(port >> 8)); req.Add((byte)(port & 0xff));
            byte[] rq = req.ToArray();
            ns.Write(rq, 0, rq.Length);
            byte[] rh = new byte[4];
            if (ns.Read(rh, 0, 4) != 4 || rh[0] != 5 || rh[1] != 0) { tc.Close(); return null; }
            int atyp = rh[3];
            int skip = atyp == 1 ? 6 : atyp == 4 ? 18 : 0;
            if (atyp == 3) { skip = ns.ReadByte() + 2; }
            for (int i = 0; i < skip; i++) ns.ReadByte();
            return ns;
        }

        // Downloads `bytes` from host over a freshly established SOCKS5 stream
        // (username gives it an isolated circuit). Returns bytes received.
        private static long SocksDownload(string host, string username, long bytes)
        {
            try
            {
                NetworkStream ns = Socks5Connect(host, 443, username);
                if (ns == null) return -1;
                using (var ssl = new System.Net.Security.SslStream(ns))
                {
                    ssl.AuthenticateAsClient(host, null,
                        System.Security.Authentication.SslProtocols.Tls12, false);
                    byte[] req = Encoding.ASCII.GetBytes(
                        "GET /__down?bytes=" + bytes + " HTTP/1.1\r\n" +
                        "Host: " + host + "\r\n" +
                        "User-Agent: start-tor-speedtest/1.0\r\n" +
                        "Connection: close\r\n\r\n");
                    ssl.Write(req, 0, req.Length);
                    ssl.Flush();
                    byte[] buf = new byte[64 * 1024];
                    long total = 0;
                    int n;
                    while ((n = ssl.Read(buf, 0, buf.Length)) > 0) total += n;
                    return total;
                }
            }
            catch { return -1; }
        }

        // The "ultimate" speed test: N parallel SOCKS5 streams, each with its own
        // username -> its own circuit. This is the max-throughput configuration
        // the strategies are aiming for.
        private static void MultiSpeedTest(int streams)
        {
            Console.WriteLine();
            Console.WriteLine("Max speed test: " + streams + " parallel streams " +
                              "(each on its own circuit via SOCKS5 auth)...");
            string host = "speed.cloudflare.com";
            long target = 10L * 1024 * 1024;
            long total = 0;
            var lockObj = new object();
            var errors = new List<string>();
            var threads = new List<Thread>();
            Stopwatch sw = Stopwatch.StartNew();
            for (int i = 0; i < streams; i++)
            {
                string user = "torb" + i; // unique -> isolated circuit
                Thread th = new Thread(delegate()
                {
                    long got = SocksDownload(host, user, target);
                    if (got < 0)
                    {
                        lock (lockObj) { if (errors.Count == 0) errors.Add("stream " + user + " failed"); }
                        got = 0;
                    }
                    Interlocked.Add(ref total, got);
                });
                th.IsBackground = true;
                threads.Add(th);
                th.Start();
            }
            foreach (Thread th in threads) th.Join();
            sw.Stop();
            double avg = total / sw.Elapsed.TotalSeconds;
            Console.WriteLine("Done: " + total.ToString("#,0") + " bytes in " +
                              sw.Elapsed.TotalSeconds.ToString("0.0") + " s");
            Console.WriteLine("  aggregate average : " + FormatSpeed(avg));
            if (errors.Count > 0) Console.WriteLine("  [i] " + errors.Count + " of " + streams + " streams failed");
        }

        private static void SpeedTestMenu()
        {
            Console.WriteLine();
            Console.WriteLine("  Speed test:");
            Console.WriteLine("    1) Single stream (HTTP 8118)");
            Console.WriteLine("    2) Max: " + StrategyNames.Length + "+ parallel SOCKS5 streams, each own circuit");
            Console.Write("  Choose 1-2 (Enter = 2): ");
            string input;
            try { input = Console.ReadLine(); }
            catch { input = "2"; }
            if (string.IsNullOrWhiteSpace(input)) input = "2";
            int n;
            if (!int.TryParse(input.Trim(), out n)) n = 2;
            if (n == 1) SpeedTest();
            else MultiSpeedTest(4);
        }

        // --- benchmark / conflux diagnostics (step 0 harness) --------------

        private static byte[] HexToBytes(string hex)
        {
            byte[] b = new byte[hex.Length / 2];
            for (int i = 0; i < b.Length; i++)
                b[i] = Convert.ToByte(hex.Substring(i * 2, 2), 16);
            return b;
        }

        // Sends a command to the tor control port and returns the response
        // payload lines (without the terminating status line).
        private static List<string> ControlCommand(string cmd)
        {
            try
            {
                string hex = CookieHex();
                if (hex == null) return null;
                using (TcpClient c = new TcpClient("127.0.0.1", 9051))
                {
                    NetworkStream s = c.GetStream();
                    StreamWriter w = new StreamWriter(s) { NewLine = "\r\n", AutoFlush = true };
                    StreamReader r = new StreamReader(s);
                    w.WriteLine("AUTHENTICATE " + hex);
                    string a = r.ReadLine();
                    if (a == null || !a.StartsWith("250")) return null;
                    w.WriteLine(cmd);
                    var lines = new List<string>();
                    string line;
                    while ((line = r.ReadLine()) != null)
                    {
                        if (line.StartsWith("250 ")) break;
                        if (line.StartsWith("250-")) lines.Add(line.Substring(4));
                        else if (line.StartsWith("250+")) lines.Add(line.Substring(4));
                        else lines.Add(line);
                    }
                    try { w.WriteLine("QUIT"); } catch { }
                    return lines;
                }
            }
            catch { return null; }
        }

        // Extracts the exit fingerprint ($hex) from a circuit-status line.
        private static string ExtractExit(string line)
        {
            foreach (string tok in line.Split(' '))
            {
                if (tok.Length > 1 && tok[0] == '$' && tok.IndexOf(',') >= 0)
                {
                    string exit = tok.Substring(tok.LastIndexOf(',') + 1);
                    int tilde = exit.IndexOf('~');
                    if (tilde >= 0) exit = exit.Substring(0, tilde);
                    return exit;
                }
            }
            return "?";
        }

        private static string ExtractConfluxId(string line)
        {
            foreach (string tok in line.Split(' '))
                if (tok.StartsWith("CONFLUX_ID="))
                    return tok.Substring("CONFLUX_ID=".Length);
            return null;
        }

        // Advertised bandwidth (bytes/s) of an exit, from GETINFO ns/id/<fp>.
        private static string ExitBandwidth(string fpHex)
        {
            try
            {
                fpHex = fpHex.TrimStart('$');
                if (fpHex == "?" || fpHex.Length != 40) return "?";
                var lines = ControlCommand("GETINFO ns/id/" + fpHex);
                if (lines == null) return "?";
                foreach (string raw in lines)
                {
                    string line = raw.Trim();
                    if (line.StartsWith("w "))
                    {
                        Match m = Regex.Match(line, "Bandwidth=(\\d+)");
                        if (m.Success) return m.Groups[1].Value;
                    }
                }
            }
            catch { }
            return "?";
        }

        // Counts conflux sets/legs and returns the exit of the first set.
        private static string ConfluxInfo(out int sets, out int legs)
        {
            sets = 0;
            legs = 0;
            string exit = "?";
            var legCount = new Dictionary<string, int>();
            var lines = ControlCommand("GETINFO circuit-status");
            if (lines == null) return exit;
            foreach (string raw in lines)
            {
                string line = raw.Trim();
                if (line.Length == 0 || line.StartsWith("circuit-status=")) continue;
                if (line.Split(' ').Length < 3) continue;
                string cid = ExtractConfluxId(line);
                if (cid != null)
                {
                    if (!legCount.ContainsKey(cid)) legCount[cid] = 0;
                    legCount[cid]++;
                    string e = ExtractExit(line);
                    if (exit == "?" && e != "?") exit = e;
                }
            }
            sets = legCount.Count;
            foreach (int n in legCount.Values) legs += n;
            return exit;
        }

        private static int ConfluxStatus()
        {
            var lines = ControlCommand("GETINFO circuit-status");
            if (lines == null)
            {
                Console.WriteLine("[x] cannot reach tor control port on 127.0.0.1:9051 (is tor running?).");
                return 1;
            }
            int total = 0;
            var sets = new Dictionary<string, List<string>>();
            bool debug = Environment.GetEnvironmentVariable("BENCH_DEBUG") == "1";
            foreach (string raw in lines)
            {
                string line = raw.Trim();
                if (line.Length == 0 || line.StartsWith("circuit-status=")) continue;
                if (debug) Console.WriteLine("    raw: " + line);
                if (line.Split(' ').Length < 3) continue;
                total++;
                string cid = ExtractConfluxId(line);
                if (cid != null)
                {
                    if (!sets.ContainsKey(cid)) sets[cid] = new List<string>();
                    sets[cid].Add(line);
                }
            }
            int legs = 0;
            foreach (var kv in sets) legs += kv.Value.Count;

            Console.WriteLine();
            Console.WriteLine("Conflux status:");
            Console.WriteLine("  total circuits    : " + total);
            Console.WriteLine("  conflux sets      : " + sets.Count);
            Console.WriteLine("  conflux legs      : " + legs);
            int idx = 1;
            foreach (var kv in sets)
            {
                string rtt = "?";
                string exit = "?";
                foreach (string leg in kv.Value)
                {
                    foreach (string tok in leg.Split(' '))
                        if (tok.StartsWith("CONFLUX_RTT=")) rtt = tok.Substring("CONFLUX_RTT=".Length);
                    string e = ExtractExit(leg);
                    if (exit == "?" && e != "?") exit = e;
                }
                Console.WriteLine("    set " + idx + ": " + kv.Value.Count + " leg(s), exit " +
                                  exit + ", RTT " + rtt);
                if (debug) Console.WriteLine("      [bw] exit bandwidth: " + ExitBandwidth(exit) + " bytes/s");
                idx++;
            }
            if (sets.Count == 0)
                Console.WriteLine("  [i] NO conflux circuits - conflux is NOT engaging (check consensus support).");
            else
                Console.WriteLine("  [i] conflux is ACTIVE (" + sets.Count + " set(s), " + legs + " leg(s)).");
            return sets.Count > 0 ? 0 : 1;
        }

        // Returns tor's own bootstrap status. Two sources are used and the more
        // advanced one wins:
        //   - the control port (GETINFO status/bootstrap-phase) is authoritative;
        //   - the log fallback ("Bootstrapped NN% (tag)") covers the window
        //     before the control port answers and guards against the launcher
        //     missing the 100% line because it scrolled out of the log tail.
        // tor.log is deleted before every start, so a stale "100%" from an older
        // run can never be misread as the current run's status.
        // Returns false when neither source has a percentage yet.
        private static bool BootstrapPhase(out int pct, out string tag, out string summary)
        {
            pct = -1;
            tag = "";
            summary = "";
            int ctl = -1, log = -1;
            string ctlTag = "", logTag = "", ctlSummary = "";

            var lines = ControlCommand("GETINFO status/bootstrap-phase");
            if (lines != null)
            {
                foreach (string raw in lines)
                {
                    string l = raw.Trim();
                    if (l.Length == 0) continue;
                    Match m = Regex.Match(l, @"PROGRESS=(\d+)");
                    if (m.Success)
                    {
                        ctl = int.Parse(m.Groups[1].Value);
                        Match t = Regex.Match(l, @"TAG=([^\s]+)");
                        if (t.Success) ctlTag = t.Groups[1].Value;
                        Match s = Regex.Match(l, @"SUMMARY=(.*)$");
                        if (s.Success) ctlSummary = s.Groups[1].Value.Trim('"');
                        break;
                    }
                }
            }

            string tail = ReadLogTail(8192);
            MatchCollection ms = Regex.Matches(tail, @"Bootstrapped\s+(\d+)%\s*(?:\(([^)]+)\))?");
            if (ms.Count > 0)
            {
                Match m = ms[ms.Count - 1];
                log = int.Parse(m.Groups[1].Value);
                if (m.Groups[2].Success) logTag = m.Groups[2].Value;
            }

            if (log > ctl)
            {
                pct = log;
                tag = logTag;
                return true;
            }
            if (ctl >= 0)
            {
                pct = ctl;
                tag = ctlTag;
                summary = ctlSummary;
                return true;
            }
            return false;
        }

        // Redraws the bootstrap progress bar on the current console line.
        // The percentage is snapped to 10% steps (0, 10, 20, ..., 100).
        private static void DrawProgress(int pct, string label)
        {
            const int width = 24;
            pct = (pct / 10) * 10;
            if (pct > 100) pct = 100;
            if (pct < 0) pct = 0;
            int filled = (int)Math.Round(pct / 100.0 * width);
            if (filled > width) filled = width;
            if (filled < 0) filled = 0;
            string bar = new string('#', filled) + new string('.', width - filled);
            string line = "    [" + bar + "] " + pct.ToString() + "%";
            if (!string.IsNullOrEmpty(label)) line += "  " + label;
            if (line.Length < progressLineLen) line = line.PadRight(progressLineLen);
            Console.Write("\r" + line);
            progressLineLen = line.Length;
        }

        private static void ClearProgressLine()
        {
            if (progressLineLen > 0)
            {
                Console.Write("\r" + new string(' ', progressLineLen) + "\r");
                progressLineLen = 0;
            }
        }

        // Starts tor for the given mode, writes torrc, stops any previous run,
        // and waits until bootstrap reaches 100%. Returns the process or null.
        private static Process StartTorAndWait(int mode, int strategy, out string errorMessage)
        {
            errorMessage = null;
            if (!File.Exists(TorExe))
            {
                errorMessage = "tor.exe not found in " + DataDir;
                return null;
            }
            if (!WriteTorrc(mode, strategy))
            {
                errorMessage = "failed to write torrc (bridge file missing?).";
                return null;
            }
            StopPreviousRun();
            Directory.CreateDirectory(Path.Combine(DataDir, "data"));
            try { if (File.Exists(TorLog)) File.Delete(TorLog); } catch { }

            ProcessStartInfo psi = new ProcessStartInfo
            {
                FileName = TorExe,
                Arguments = "-f \"torrc\"",
                WorkingDirectory = DataDir,
                UseShellExecute = false,
                CreateNoWindow = true
            };
            Process proc;
            try { proc = Process.Start(psi); }
            catch (Exception ex)
            {
                errorMessage = "failed to start tor: " + ex.Message;
                return null;
            }
            torProc = proc;
            Console.WriteLine("[i] tor started (PID " + proc.Id + "), bootstrapping...");

            DateTime deadline = DateTime.UtcNow.AddMinutes(10);
            int lastPct = -1;
            string lastTag = "";
            DateTime stuckSince = DateTime.UtcNow;
            while (DateTime.UtcNow < deadline)
            {
                try { proc.Refresh(); } catch { }
                if (proc.HasExited)
                {
                    ClearProgressLine();
                    errorMessage = "tor exited with code " + proc.ExitCode + ".\n" + ReadLogTail(1500);
                    return null;
                }
                int pct;
                string tag;
                string summary;
                if (BootstrapPhase(out pct, out tag, out summary))
                {
                    if (pct >= 100)
                    {
                        DrawProgress(100, tag);
                        Console.WriteLine();
                        progressLineLen = 0;
                        return proc;
                    }
                    if (pct != lastPct)
                    {
                        lastPct = pct;
                        lastTag = tag;
                        stuckSince = DateTime.UtcNow;
                        DrawProgress(pct, tag);
                    }
                    else if (DateTime.UtcNow - stuckSince > TimeSpan.FromMinutes(3))
                    {
                        DrawProgress(pct, tag + "  (still waiting...)");
                    }
                    else
                    {
                        DrawProgress(pct, tag);
                    }
                }
                Thread.Sleep(1500);
            }
            ClearProgressLine();
            errorMessage = "bootstrap did not reach 100% in 10 minutes (last seen: " +
                           lastPct + "% " + lastTag + ").\n" + ReadLogTail(1500);
            return null;
        }

        private static string benchUrl;
        private static readonly string[] BenchEndpoints =
        {
            "https://speed.cloudflare.com/__down?bytes=10485760",
            "https://speed.hetzner.de/10MB.bin",
            "http://speedtest.tele2.net/10MB.zip"
        };

        // Picks the first speed endpoint reachable through the proxy.
        private static void ProbeBenchUrl()
        {
            foreach (string u in BenchEndpoints)
            {
                try
                {
                    HttpWebRequest req = (HttpWebRequest)WebRequest.Create(u);
                    req.Proxy = new WebProxy("127.0.0.1", 8118);
                    req.Method = "GET";
                    req.Timeout = 30000;
                    req.ReadWriteTimeout = 30000;
                    req.UserAgent = "start-tor-speedtest/1.0";
                    using (WebResponse resp = req.GetResponse())
                    using (Stream s = resp.GetResponseStream())
                    {
                        byte[] buf = new byte[16384];
                        if (s.Read(buf, 0, buf.Length) > 0)
                        {
                            benchUrl = u;
                            Console.WriteLine("[i] speed endpoint OK: " + u);
                            return;
                        }
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine("[i] endpoint failed (" + u + "): " + ex.Message);
                }
            }
            benchUrl = null;
            Console.WriteLine("[!] no speed endpoint reachable through the proxy.");
        }

        // Downloads `bytesPerStream` through the proxy on `streams` parallel
        // connections and reports aggregate throughput + peak sampled rate.
        private static void BenchDownload(int streams, long bytesPerStream,
                                          out long total, out double secs, out double peak)
        {
            long totalBytes = 0;
            long lastBytes = 0;
            double lastElapsed = 0;
            double peakRate = 0;
            var errors = new List<string>();
            Stopwatch sw = new Stopwatch();
            sw.Start();
            var threads = new List<Thread>();
            for (int i = 0; i < streams; i++)
            {
                Thread th = new Thread(delegate()
                {
                    long got = 0;
                    try
                    {
                        HttpWebRequest req = (HttpWebRequest)WebRequest.Create(
                            benchUrl ?? BenchEndpoints[0]);
                        req.Proxy = new WebProxy("127.0.0.1", 8118);
                        req.Method = "GET";
                        req.Timeout = 180000;
                        req.ReadWriteTimeout = 180000;
                        req.UserAgent = "start-tor-speedtest/1.0";
                        using (WebResponse resp = req.GetResponse())
                        using (Stream s = resp.GetResponseStream())
                        {
                            byte[] buf = new byte[64 * 1024];
                            int n;
                            while ((n = s.Read(buf, 0, buf.Length)) > 0) got += n;
                        }
                    }
                    catch (Exception ex)
                    {
                        lock (errors) errors.Add(ex.Message);
                    }
                    Interlocked.Add(ref totalBytes, got);
                });
                th.IsBackground = true;
                threads.Add(th);
                th.Start();
            }
            while (true)
            {
                bool alive = false;
                foreach (Thread th in threads) if (th.IsAlive) { alive = true; break; }
                if (!alive) break;
                Thread.Sleep(200);
                double el = sw.Elapsed.TotalSeconds;
                long tb = Interlocked.Read(ref totalBytes);
                double dt = el - lastElapsed;
                if (dt >= 1.0)
                {
                    double rate = (tb - lastBytes) / dt;
                    if (rate > peakRate) peakRate = rate;
                    lastBytes = tb;
                    lastElapsed = el;
                }
            }
            sw.Stop();
            total = Interlocked.Read(ref totalBytes);
            secs = sw.Elapsed.TotalSeconds;
            double finalDt = secs - lastElapsed;
            if (finalDt > 0.2)
            {
                double r = (total - lastBytes) / finalDt;
                if (r > peakRate) peakRate = r;
            }
            peak = peakRate;
            if (errors.Count > 0 && total == 0)
            {
                lock (errors)
                {
                    Console.WriteLine("      [err] " + (errors.Count == 1 ? errors[0] :
                        errors[0] + " (+" + (errors.Count - 1) + " more)"));
                }
            }
        }

        private static void RunBench(int mode, int iters, int[] streamCounts, string csvPath)
        {
            string err;
            Process proc = StartTorAndWait(mode, ResolveStrategy(), out err);
            if (proc == null)
            {
                Console.WriteLine("[x] " + err);
                Cleanup();
                return;
            }
            try
            {
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
                ServicePointManager.DefaultConnectionLimit = 64;
            }
            catch { }

            Console.WriteLine("[i] bootstrap OK. Warming up 30s (building conflux legs)...");
            Thread.Sleep(30000);
            ProbeBenchUrl();
            if (benchUrl == null)
            {
                Console.WriteLine("[x] aborting bench: no reachable speed endpoint.");
                Cleanup();
                return;
            }

            string variant = Environment.GetEnvironmentVariable("BENCH_VARIANT") ?? "";
            bool writeHeader = !File.Exists(csvPath) || new FileInfo(csvPath).Length == 0;
            var rows = new StringBuilder();
            if (writeHeader)
                rows.AppendLine("ts,variant,mode,streams,avg_mbps,peak_mbps,total_bytes,exit_fp,exit_bw,conflux_sets,conflux_legs");

            foreach (int sc in streamCounts)
            {
                for (int i = 0; i < iters; i++)
                {
                    Console.WriteLine("  [" + (variant.Length > 0 ? variant : ModeNames[mode]) +
                                      "] streams=" + sc + " iter=" + (i + 1) + " ...");
                    long total;
                    double secs, peak;
                    BenchDownload(sc, 10L * 1024 * 1024, out total, out secs, out peak);
                    double avg = secs > 0 ? total / secs : 0;
                    Console.WriteLine("      avg " + FormatSpeed(avg) + "  peak " + FormatSpeed(peak) +
                                      "  in " + secs.ToString("0.0") + " s");
                    int cSets, cLegs;
                    string exit = ConfluxInfo(out cSets, out cLegs);
                    string bw = ExitBandwidth(exit);
                    rows.AppendLine(string.Join(",",
                        DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss"),
                        Csv(variant), ModeNames[mode], sc.ToString(),
                        (avg / (1024 * 1024)).ToString("0.000"),
                        (peak / (1024 * 1024)).ToString("0.000"),
                        total.ToString(), exit, bw, cSets.ToString(), cLegs.ToString()));
                }
            }
            try { File.AppendAllText(csvPath, rows.ToString(), new UTF8Encoding(false)); }
            catch (Exception ex) { Console.WriteLine("[x] failed to write CSV: " + ex.Message); }
            Console.WriteLine("[i] CSV appended to " + csvPath);

            int s2, l2;
            string e2 = ConfluxInfo(out s2, out l2);
            Console.WriteLine("[i] conflux at end: " + s2 + " set(s), " + l2 + " leg(s), exit " + e2);
            Cleanup();
        }

        private static string Csv(string s)
        {
            if (s.IndexOfAny(new[] { ',', '"', '\n', '\r' }) < 0) return s;
            return "\"" + s.Replace("\"", "\"\"") + "\"";
        }

        private static int[] ParseInts(string s)
        {
            var list = new List<int>();
            foreach (string p in s.Split(','))
            {
                int n;
                if (int.TryParse(p.Trim(), out n) && n >= 1) list.Add(n);
            }
            if (list.Count == 0) list.Add(1);
            return list.ToArray();
        }

        private static int StopTor()
        {
            Process p = FindTor();
            if (p != null)
            {
                try { p.Kill(); p.WaitForExit(5000); } catch { }
                SetSystemProxy(false);
                Console.WriteLine("Tor stopped; system proxy restored.");
            }
            else
            {
                Console.WriteLine("No tor from this folder is running.");
            }
            return 0;
        }

        // --- startup port check --------------------------------------------
        // If the TorBoost ports are already occupied, a previous tor instance is
        // still running: stop it (and any leftover TUN/system proxy), then carry
        // on with a fresh start instead of refusing to launch.
        private static bool TcpPortBusy(int port)
        {
            TcpListener l = null;
            try
            {
                l = new TcpListener(IPAddress.Loopback, port);
                l.Start();
                return false;
            }
            catch (SocketException) { return true; }
            finally
            {
                if (l != null) try { l.Stop(); } catch { }
            }
        }

        private static bool UdpPortBusy(int port)
        {
            try
            {
                using (UdpClient u = new UdpClient(new IPEndPoint(IPAddress.Loopback, port)))
                { }
                return false;
            }
            catch (SocketException) { return true; }
        }

        private static bool PreviousRunActive()
        {
            foreach (int p in TcpPorts)
                if (TcpPortBusy(p)) return true;
            return UdpPortBusy(UdpDnsPort);
        }

        private static void StopPreviousRun()
        {
            Process running = FindTor();
            bool prev = running != null || PreviousRunActive();
            if (!prev && !TunActive()) return;

            Console.WriteLine("  [i] A previous TorBoost run is still active - stopping it.");

            if (TunActive())
            {
                Console.WriteLine("  [i] Stopping previous TUN...");
                try { File.WriteAllText(TunStopFile, "stop", new UTF8Encoding(false)); } catch { }
                for (int i = 0; i < 16 && TunActive(); i++) Thread.Sleep(500);
                if (TunActive())
                    try { SpawnElevated("off", true); } catch { }
            }

            if (prev)
            {
                var victims = new List<Process>();
                try
                {
                    foreach (Process p in Process.GetProcessesByName("tor"))
                    {
                        try
                        {
                            string path;
                            try { path = p.MainModule.FileName; }
                            catch { path = null; }
                            if (path == null ||
                                StringComparer.OrdinalIgnoreCase.Equals(
                                    Path.GetFullPath(path), Path.GetFullPath(TorExe)))
                                victims.Add(p);
                        }
                        catch { }
                    }
                }
                catch { }
                if (running != null && !victims.Exists(v => v.Id == running.Id))
                    victims.Add(running);
                foreach (Process p in victims)
                {
                    try
                    {
                        Console.WriteLine("  [i] Stopping previous tor (PID " + p.Id + ")...");
                        p.Kill();
                        p.WaitForExit(5000);
                    }
                    catch { }
                }
                Thread.Sleep(1500);
            }

            SetSystemProxy(false);
        }

        // Runs one Tor session: writes torrc, boots tor with a live progress
        // bar, then serves the P/T/S/C keys until the user presses C or tor
        // dies. Returns 0 (clean exit), 1 (error) or 2 (return to main menu).
        private static int RunTorSession(int mode, int strategy, bool genOnly,
                                         bool bootstrapOnly, string autoMode,
                                         bool menuReturn)
        {
            if (!File.Exists(TorExe))
            {
                Console.WriteLine("[x] tor.exe not found in " + DataDir);
                WaitForKey();
                return 1;
            }
            if (genOnly)
            {
                if (!WriteTorrc(mode, strategy)) { WaitForKey(); return 1; }
                Console.WriteLine("[i] torrc written only (test mode, tor not started): " + Torrc);
                return 0;
            }

            string startErr;
            torProc = StartTorAndWait(mode, strategy, out startErr);
            if (torProc == null)
            {
                Console.WriteLine("[x] " + startErr);
                Cleanup();
                cleaned = false;
                if (menuReturn)
                {
                    Console.WriteLine();
                    Console.WriteLine("Press any key to return to the menu...");
                    try { Console.ReadKey(true); } catch { }
                    return 2;
                }
                WaitForKey();
                return 1;
            }

            Console.WriteLine();
            Console.WriteLine("Bootstrapped 100% - Tor is UP.");
            Console.WriteLine();

            if (bootstrapOnly)
            {
                Console.WriteLine("Test mode: stopping tor (no proxy change).");
                Cleanup();
                return 0;
            }

            bool proxyOn = false;
            if (autoMode == "proxy")
            {
                proxyOn = true;
                SetSystemProxy(true);
                Console.WriteLine("  [i] System proxy ON  (127.0.0.1:8118)");
            }
            else if (autoMode == "tun")
            {
                if (TunActive())
                    Console.WriteLine("  [i] TUN already ON");
                else
                    ToggleTun();
            }
            Console.WriteLine("  P               toggle the Windows system proxy on/off");
            Console.WriteLine("  T               toggle TUN mode (all traffic through Tor)");
            Console.WriteLine("  S               run a speed test through the Tor proxy");
            Console.WriteLine("  C               stop Tor and " + (menuReturn ? "return to the menu" : "exit"));
            Console.WriteLine();
            while (true)
            {
                bool alive = true;
                if (torProc != null)
                {
                    try { torProc.Refresh(); alive = !torProc.HasExited; }
                    catch { alive = false; }
                }
                if (!alive)
                {
                    Console.WriteLine("[x] tor exited with code " + (torProc != null ? torProc.ExitCode : -1) + ".");
                    break;
                }
                try
                {
                    if (Console.KeyAvailable)
                    {
                        ConsoleKeyInfo ki = Console.ReadKey(true);
                        if (ki.Key == ConsoleKey.P)
                        {
                            proxyOn = !proxyOn;
                            SetSystemProxy(proxyOn);
                            Console.WriteLine("  [i] System proxy " + (proxyOn ? "ON  (127.0.0.1:8118)" : "OFF"));
                        }
                        else if (ki.Key == ConsoleKey.S)
                        {
                            SpeedTestMenu();
                        }
                        else if (ki.Key == ConsoleKey.T)
                        {
                            ToggleTun();
                        }
                        else if (ki.Key == ConsoleKey.C)
                        {
                            Console.WriteLine();
                            Console.WriteLine("  [i] Stopping Tor...");
                            Cleanup();
                            cleaned = false;
                            torProc = null;
                            Console.WriteLine("  [i] Tor stopped; system proxy restored.");
                            Console.WriteLine();
                            return menuReturn ? 2 : 0;
                        }
                    }
                }
                catch { }
                Thread.Sleep(150);
            }

            Cleanup();
            cleaned = false;
            Console.WriteLine("Tor stopped; system proxy restored.");
            WaitForKey();
            return 0;
        }

        private static int Main(string[] args)
        {
            Console.Title = "TorBoost";
            Console.CancelKeyPress += delegate(object sender, ConsoleCancelEventArgs e)
            {
                e.Cancel = true;
                Cleanup();
                Environment.Exit(0);
            };

            if (args.Length > 0 && args[0] == "--conflux-status")
            {
                return ConfluxStatus();
            }
            if (args.Length > 0 && args[0] == "--conflux-check")
            {
                int m = -1;
                for (int i = 1; i < args.Length; i++) { int mm = ParseMode(args[i]); if (mm >= 0) m = mm; }
                if (m < 0) m = ShowMenu();
                if (m < 0) { Console.WriteLine("[x] no mode selected."); return 1; }
                string err;
                Process p = StartTorAndWait(m, ResolveStrategy(), out err);
                if (p == null) { Console.WriteLine("[x] " + err); Cleanup(); return 1; }
                Console.WriteLine("[i] bootstrap OK. Waiting 30s for conflux sets to build...");
                Thread.Sleep(30000);
                int code = ConfluxStatus();
                Cleanup();
                return code;
            }
            if (args.Length > 0 && args[0] == "--bench")
            {
                int bMode = -1;
                int iters = 3;
                int[] streams = { 1, 4, 8 };
                string csvPath = "bench.csv";
                for (int i = 1; i < args.Length; i++)
                {
                    if (args[i] == "--iters" && i + 1 < args.Length) { int.TryParse(args[++i], out iters); }
                    else if (args[i] == "--streams" && i + 1 < args.Length) { streams = ParseInts(args[++i]); }
                    else if (args[i] == "--csv" && i + 1 < args.Length) { csvPath = args[++i]; }
                    else { int mm = ParseMode(args[i]); if (mm >= 0) bMode = mm; }
                }
                if (bMode < 0) bMode = ShowMenu();
                if (bMode < 0) return 1;
                RunBench(bMode, iters, streams, csvPath);
                return 0;
            }
            if (args.Length > 0 && args[0] == "--newcircuit")
            {
                Console.WriteLine(ControlSend("SIGNAL NEWNYM")
                    ? "New identity requested (NEWNYM)."
                    : "No tor control port on 127.0.0.1:9051. Is tor running?");
                return 0;
            }
            if (args.Length > 0 && args[0] == "--stop")
            {
                return StopTor();
            }
            if (args.Length > 0 &&
                (args[0] == "--update-bridges" || args[0] == "--update" || args[0] == "-u"))
            {
                return UpdateBridges();
            }
            if (args.Length > 0 && args[0] == "--tun-off")
            {
                if (!TunActive())
                {
                    Console.WriteLine("TUN OFF");
                    return 0;
                }
                TurnTunOff();
                return TunActive() ? 1 : 0;
            }
            if (args.Length > 0 && args[0] == "--tun-status")
            {
                Console.WriteLine("TUN " + (TunActive() ? "ON" : "OFF"));
                return 0;
            }

            int mode = -1;
            int strategy = -1;
            bool bootstrapOnly = false;
            bool genOnly = false;
            string autoMode = "";
            for (int i = 0; i < args.Length; i++)
            {
                string a = args[i];
                if (a == "--bootstrap-only" || a == "-t") bootstrapOnly = true;
                else if (a == "--gen-torrc-only") genOnly = true;
                else if (a == "--strategy" && i + 1 < args.Length) strategy = ParseStrategy(args[++i]);
                else if (a == "--strategy") strategy = ParseStrategy(a);
                else if (a == "proxy" || a == "--proxy") autoMode = "proxy";
                else if (a == "tun" || a == "--tun") autoMode = "tun";
                else
                {
                    int m = ParseMode(a);
                    if (m >= 0) { mode = m; continue; }
                    int s = ParseStrategy(a);
                    if (s >= 0) strategy = s;
                }
            }
            if (mode < 0)
            {
                while (true)
                {
                    ShowMainMenu(out mode, out strategy);
                    if (mode < 0) return 0;
                    int rc = RunTorSession(mode, strategy, genOnly, bootstrapOnly, autoMode, true);
                    if (rc != 2) return rc;
                }
            }
            else
            {
                if (strategy < 0) strategy = ReadLastStrategy();
                if (strategy < 0) strategy = 0;
                return RunTorSession(mode, strategy, genOnly, bootstrapOnly, autoMode, false);
            }
        }
    }
}
